### ISSUE TITLE
feat(ui): implement search page

### ISSUE THREAD

**Issue by cEvolve05** [NJUPT-SAST/sast-evento#13]
实现部门活动，展示活动，根据部门筛选活动，对部门进行订阅，搜索框不用写，可以考虑自己美化一下设计，考虑实现根据页面大小自动换行

files:
- `ui\views\page\search.slint`
- `src\Controller\View\SearchPage.h`
- `src\Controller\View\SearchPage.cc`

参考：[wiki](https://github.com/NJUPT-SAST/sast-evento/wiki)

**Comment by Serein207** [comment]
订阅部门功能（侧面部门列表的⭐）先不做

搜索框主要是直接搜索部门名称再筛选用的，本地关键词检索就可以了
